### ISSUE TITLE
No opp_sliding_window in utils

### ISSUE THREAD

**Issue by KevinHooah** [Hangwei12358/cross-person-HAR#2]
Hi,

I am running the Opportunity example, I found there isn't opp_sliding_window function in the utils.py. For the Opportunity example, even this function isn't needed, I think you may update the importing code. Thanks.

**Comment by Hangwei12358** [comment]
Hi,

Please remove `opp_sliding_window` from the code, and the `opp_sliding_window_w_d` function can work well. 

Thank you.
